apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1048576k
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: registry
    namespace: harbor
  hostPath:
    path: /harbor/registry
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry
  namespace: harbor
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1048576k
  volumeMode: Filesystem
  volumeName: registry-pv
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1048576k
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: chartmuseum-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1048576k
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: chartmuseum
    namespace: harbor
  hostPath:
    path: /harbor/chartmuseum
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chartmuseum
  namespace: harbor
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1048576k
  volumeMode: Filesystem
  volumeName: chartmuseum-pv
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1048576k
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jobservice-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1048576k
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jobservice
    namespace: harbor
  hostPath:
    path: /harbor/jobservice
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jobservice
  namespace: harbor
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1048576k
  volumeMode: Filesystem
  volumeName: jobservice-pv
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1048576k
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1048576k
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: database
    namespace: harbor
  hostPath:
    path: /harbor/database
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
  namespace: harbor
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1048576k
  volumeMode: Filesystem
  volumeName: database-pv
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1048576k
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1048576k
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: redis
    namespace: harbor
  hostPath:
    path: /harbor/redis
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: harbor
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1048576k
  volumeMode: Filesystem
  volumeName: redis-pv
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1048576k
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: trivy-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1048576k
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: trivy
    namespace: harbor
  hostPath:
    path: /harbor/trivy
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trivy
  namespace: harbor
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1048576k
  volumeMode: Filesystem
  volumeName: trivy-pv
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1048576k

